### ISSUE TITLE
API doesn't work with PHP versions greater than 5.6

### ISSUE THREAD

**Issue by Thiggel** [woocommerce/wc-api-php#162]
Hey Guys,

I built a working app using your API. But since I updated my PHP version from 5.4 to 7.1, the app doesn't work anymore. I get the following error:

`Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Syntax error in /Applications/MAMP/htdocs/ProductCreatorOld/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:346 Stack trace: #0 /Applications/MAMP/htdocs/ProductCreatorOld/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(385): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 /Applications/MAMP/htdocs/ProductCreatorOld/vendor/automattic/woocommerce/src/WooCommerce/Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'POST', Array) #2 /Applications/MAMP/htdocs/ProductCreatorOld/WooCommerceCon.php(135): Automattic\WooCommerce\Client->post('products', Array) #3 /Applications/MAMP/htdocs/ProductCreatorOld/ProductCreator.php(61): WooCommerceCon->createProducts(Array) #4 /Applications/MAMP/htdocs/ProductCreatorOld/ProductCreator.php(68): synch() #5 {main} thrown in /Applications/MAMP/htdocs/ProductCreatorOld/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 346`

It seems that PHP's Http-Classes work a little different in PHP 7 or have become deprecated.. 

Thanks for the help!

**Comment by Mr-AjayM** [comment]
@Thiggel. Currently, I have also working with the WooCommerce REST API for Developing Mobile Apps. It seems working fine in PHP7 as well.
