### ISSUE TITLE
Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]

### ISSUE THREAD

**Issue by yichenlovetj** [woocommerce/wc-api-php#214]
I am getting this error when my plugin running for about 10 mins, I am doing a ajax call to update a list of Woocommerce product attributes, so the log looks like it is running for a while and suddenly the server stops this call,  here is my config:

$this->wcapi = new WooCommerce\Client( 
		$this->url,
		$this->consumer_key, 
		$this->consumer_secret, 
		[
        'wp_api' => true,
        'version' => 'wc/v2',
         'verify_ssl' => false,
        ]);

Error log:

[27-Jul-2018 15:18:05 UTC] update product: 8763
[27-Jul-2018 15:20:38 UTC] update product: 8768
[27-Jul-2018 15:23:20 UTC] update product: 8775
[27-Jul-2018 15:25:49 UTC] update product: 8789
[27-Jul-2018 15:28:06 UTC] update product: 7701
[27-Jul-2018 15:30:24 UTC] update product: 542
[27-Jul-2018 15:32:48 UTC] update product: 8756
[27-Jul-2018 15:32:58 UTC] PHP Fatal error:  Uncaught AECatsy2Woocommerce\Catsy\WooCommerce\HttpClient\HttpClientException: Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view] in /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woocommerce/HttpClient/HttpClient.php:357
Stack trace:
#0 /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woocommerce/HttpClient/HttpClient.php(393): AECatsy2Woocommerce\Catsy\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass))
#1 /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woocommerce/HttpClient/HttpClient.php(429): AECatsy2Woocommerce\Catsy\WooCommerce\HttpClient\HttpClient->processResponse()
#2 /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woocommerce/Client.php(85): AECatsy2Woocommerce\Catsy\WooCommerce\HttpClient\HttpClient->request('products/attrib...', 'GET', Array, Array)
#3 /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woo in /home/kngdesign/public_html/wp-content/plugins/ae-catsy-2-woocommerce/inc/catsy/woocommerce/HttpClient/HttpClient.php on line 357

**Comment by claudiosanches** [comment]
Sounds like related to your server or installation, maybe your server started to block your requests.
Closing since doesn't like an issue with this library.
