### ISSUE TITLE
Getting PHP Fatal Error, Uncaught JSON error.

### ISSUE THREAD

**Issue by darrylmorley** [woocommerce/wc-api-php#247]
Hi,

I am getting the following error when trying to return woocommerce products:

```
PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array)
#2 /Users/darryl/dev/shootingsupplies/wooApi-php/productimport.php(22): Automattic\WooCommerce\Client->get('products')
#3 {main}
  thrown in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array)
#2 /Users/darryl/dev/shootingsupplies/wooApi-php/productimport.php(22): Automattic\WooCommerce\Client->get('products')
#3 {main}
  thrown in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

[Done] exited with code=255 in 0.083 seconds
```

**Comment by darrylmorley** [comment]
Hi,

I have it set as v3. I currently have a local dev site, set up as ss-wordpress.test.

In my file I have:

```
<?php
// Install:
// composer require automattic/woocommerce

// Setup:
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'localhost', // Your store URL
    'ck_85095c174dfa092e1283204623e74eca7a046483', // Your consumer key
    'cs_2992796534ebb1fecca434380e62021acd448280', // Your consumer secret
    [
        'wp_api' => true, // Enable the WP REST API integration
        'version' => 'wc/v3',  // WooCommerce WP REST API version
        'verify_ssl' => false
    ]
);
?>

<?php print_r($woocommerce->get('products')); ?>
```

The result I get is:

```
PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array)
#2 /Users/darryl/dev/shootingsupplies/wooApi-php/productimport.php(22): Automattic\WooCommerce\Client->get('products')
#3 {main}
  thrown in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378

Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:378
Stack trace:
#0 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array)
#2 /Users/darryl/dev/shootingsupplies/wooApi-php/productimport.php(22): Automattic\WooCommerce\Client->get('products')
#3 {main}
  thrown in /Users/darryl/dev/shootingsupplies/wooApi-php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 378
```

I have tried setting the store url as both localhost and the local domain of ss-wordpress.test. I have tried both v2 and v3 api.

**Comment by t-prod** [comment]
Do you try to change permalinks settings to post name for instance ? A wrong choice in permalinks could cause this type of error :)

**Comment by sofun16** [comment]
How did you fix this error?

**Comment by mujuonly** [comment]
check URL is http or https

**Comment by sofun16** [comment]
Mine is http

**Comment by mujuonly** [comment]
Please check by changing it to https as well

**Comment by kubamichalski** [comment]
Hello all. I have the same error during connecting Woocommerce with external invoice platform. What is funny, some products are imported. I tried v2 v3 version, pretty permalinks, URL is https . 
Please, help :)

**Comment by sofun16** [comment]
Hello i change  my site using a certified https and now works.

**Comment by kubamichalski** [comment]
> Hello i change  my site using a certified https and now works.

Hello, all my site is https,  but thank you.

**Comment by waqas-mehmood-pk** [comment]
Hello all I am facing the same error. URL is https and permalink setting is post name.

**Comment by Esteban200589** [comment]
Hola, pudieron solucionar ese error?

**Comment by merciful-player** [comment]
I still have not been able to solve this issue. My problem is not with `GET`, but with `PUT`. Someone please help. This started at the beginning of May and before that, no issues.

Has anyone resolved the issue??? I'm desperate here!
