### ISSUE TITLE
JSON ERROR: Syntax error in C:\laragon\www\contactform7\HttpClient\HttpClient.php:378

### ISSUE THREAD

**Issue by peterb776** [woocommerce/wc-api-php#260]
I am trying to get the API working on my local development (laptop) server using Laragon 4 (PHP 7.2), setting up the installation without using composer as on the target system I only have limited CPanel access.

The host system is running WordPress 5.2.5 and WooCommerce 3.5.7, with the REST API enabled.

Using the following PHP code (copied from the API documentation, plus a suggested mod to deal with Laragon's self-signed certificates) as the stand-alone  index.php on another domain:
___________

```
<html>
<head>
<title>Test of WooC REST API for creating products</title>
</head>
<body>
<?php
require __DIR__ . '/HttpClient/BasicAuth.php';
require __DIR__ . '/HttpClient/HttpClient.php';
require __DIR__ . '/HttpClient/HttpClientException.php';
require __DIR__ . '/HttpClient/OAuth.php';
require __DIR__ . '/HttpClient/Options.php';
require __DIR__ . '/HttpClient/Request.php';
require __DIR__ . '/HttpClient/Response.php';

require __DIR__ . '/Client.php';

use Automattic\WooCommerce\Client;

try{
	$woocommerce = new Client(
		'http://artstrailgallerx.local',
		'ck_********a51973838e1f453036d292b3b1da327',
		'cs_********54b5c08c32e79a808fdc523a4429428c',
		[
			'wp_api'  => true,
			'version' => 'wc/v3',
			'query_string_auth' => true, // Deal with Laragon's
			'verify_ssl' => false,              // self-signed certificates
		]
	);
	echo '<p>Created API client link.</p>';
}
catch (HttpClientException $e) {
    echo '<pre><code>' . print_r( $e->getMessage(), true ) . '</code><pre>'; // Error message.
    echo '<pre><code>' . print_r( $e->getRequest(), true ) . '</code><pre>'; // Last request data.
    echo '<pre><code>' . print_r( $e->getResponse(), true ) . '</code><pre>'; // Last response data.
}
flush();

try {
print_r($woocommerce->get('products/categories'));
}
catch (HttpClientException $e) {
    echo '<pre><code>' . print_r( $e->getMessage(), true ) . '</code><pre>'; // Error message.
    echo '<pre><code>' . print_r( $e->getRequest(), true ) . '</code><pre>'; // Last request data.
    echo '<pre><code>' . print_r( $e->getResponse(), true ) . '</code><pre>'; // Last response data.
}
flush();
?>
</body>
</html>
```
____________

All I get as output is the following, with success(?) on creating the API connection but then a critical error:
____________
```
Created API client link.


Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: JSON ERROR: Syntax error in C:\laragon\www\contactform7\HttpClient\HttpClient.php:378 Stack trace: #0 C:\laragon\www\contactform7\HttpClient\HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #1 C:\laragon\www\contactform7\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'POST', Array) #2 C:\laragon\www\contactform7\index2.php(58): Automattic\WooCommerce\Client->post('products', Array) #3 {main} thrown in C:\laragon\www\contactform7\HttpClient\HttpClient.php on line 378
```
____________
Is there something else that I should be loading? If not, how can I debug this (I'm not a PHP expert)?

Thanks,
Peter

**Comment by Er-Kalpesh** [comment]
any solution for the above issue? I am facing same issue

**Comment by peterb776** [comment]
I've had no comments or suggestions, so I've made no progress. As my client needs something 'today' I've had to resort to using the WooCommerce CSV importer just to have something that works even if not very well.

I'm not happy to try and debug the API code, but might try it again sometime if there is a newer version.

**Comment by joshuatf** [comment]
Possibly related to https://github.com/woocommerce/wc-api-php/issues/256.

Are there any other testing instructions to reproduce this?  I'm not able to reproduce this on a fresh site, which probably indicates that there is either something unique about the data or there is a plugin causing the issue.
