### ISSUE TITLE
Getting a "cURL Error: Failed sending HTTP request: Header overflow in" error with 6000+products

### ISSUE THREAD

**Issue by PalmaSolutions** [woocommerce/wc-api-php#283]
When I execute a PHP script to update products in bulk I am getting this error on PHP 7.4 and Nginx with FPM and 6000+ products:

```
2020/10/02 21:26:14 [error] 24685#24685: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: cURL Error: Failed sending HTTP request: Header overflow in /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:417
Stack trace:
#0 /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request()
#1 /data/xxx/api.php(49): Automattic\WooCommerce\Client->get()
#2 {main}
  thrown in /data/xxx/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 417" while reading response header from upstream, client: 192.000.000.00 server: localhost, request: "GET /api.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "localhost"
```
Not sure where it comes from, but it seems to be a buffering issue no? Any idea on how I can fix this?

**Comment by joshuatf** [comment]
This appears to be an issue with the headers you're sending being too large.  This is a server configuration. issue and not related to this plugin.

You can either:

1. Reduce your header size within your server limits
2. Attempt to adjust your header limit sizes via Apache/Nginx
