### ISSUE TITLE
PUT request stopped working

### ISSUE THREAD

**Issue by JavaBog** [woocommerce/wc-api-php#292]
PUT requests stopped working. GET requests work fine. 
Receiving:
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Syntax error in...

Code:

`
require(APP . '/lib/vendor/autoload.php');
use Automattic\WooCommerce\Client;
/*
$woocommerce = new Client(
    'https://xxx.com', 
    'xxx', 
    'xxx',
    [
        'wp_api' => true,
        'version' => 'wc/v3',
    ]
);

$data = [
			    'status' => 'Completed'
			];
			
			print_r($woocommerce->get('orders/9362');
			print_r($woocommerce->put('orders/9362', $data));`

**Comment by JavaBog** [comment]
Looks like PUT requests just stopped working

FIX:
Send as post and add PUT method to end point

Before:
print_r($woocommerce->put('orders/xxx', $data));
After:
print_r($woocommerce->post('orders/xxx?_method=PUT', $data));

**Comment by georgosabdulnour** [comment]
i stell have this error when use PUT to update product 
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Ogiltiga parametrar: status [rest_invalid_param] in C:\xampp\htdocs\woo\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:350 Stack trace: #0 C:\xampp\htdocs\woo\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(386): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 C:\xampp\htdocs\woo\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\xampp\htdocs\woo\vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('orders/5777?_me...', 'POST', Array) #3 C:\xampp\htdocs\woo\product.php(21): Automattic\WooCommerce\Client->post('orders/5777?_me...', Array) #4 {main} thrown in C:\xampp\htdocs\woo\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 350
