### ISSUE TITLE
Fatal error unexpected character

### ISSUE THREAD

**Issue by kgatan** [woocommerce/wc-api-php#58]
Sorry to drag this here as i suspect its a server/php problem but tried forums, irc, SO and ticket and nothing so far.

Authentication works and i get the data i need but also a fatal error with "unexpected character".
Using below code,
```
<?php
header('Content-type: application/javascript');
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'url',
    'ck_***********',
    'cs_***********',
    [
        'wp_api' => true,
        'version' => 'wc/v1'
    ]
);

use Automattic\WooCommerce\HttpClient\HttpClientException;

try {
    $results = $woocommerce->get('webhooks');
} catch (HttpClientException $e) {
    \print_r($e);
    \print_r($e->getMessage() . PHP_EOL);
    \print_r('Code: ' . $e->getResponse()->getCode() . PHP_EOL);
    \print_r('Body: ' . $e->getResponse()->getBody() . PHP_EOL);
}
```

Result is,
```
Automattic\WooCommerce\HttpClient\HttpClientException Object
(
    [request:Automattic\WooCommerce\HttpClient\HttpClientException:private] => Automattic\WooCommerce\HttpClient\Request Object
        (
            [url:Automattic\WooCommerce\HttpClient\Request:private] => http://url.local/wp-json/wc/v1/webhooks?
            [method:Automattic\WooCommerce\HttpClient\Request:private] => GET
            [parameters:Automattic\WooCommerce\HttpClient\Request:private] => Array
                (
                    [oauth_consumer_key] => ck_****
                    [oauth_nonce] => *
                    [oauth_signature] => *
                    [oauth_signature_method] => HMAC-SHA256
                    [oauth_timestamp] => *
                )

            [headers:Automattic\WooCommerce\HttpClient\Request:private] => Array
                (
                    [Accept] => application/json
                    [Content-Type] => application/json
                    [User-Agent] => WooCommerce API Client-PHP/1.1.2
                )

            [body:Automattic\WooCommerce\HttpClient\Request:private] => 
        )

    [response:Automattic\WooCommerce\HttpClient\HttpClientException:private] => Automattic\WooCommerce\HttpClient\Response Object
        (
            [code:Automattic\WooCommerce\HttpClient\Response:private] => 200
            [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array
                (
                    [Date] => Mon, 24 Oct 2016 07:48:59 GMT
                    [Server] => Apache
                    [X-Robots-Tag] => noindex
                    [Link] => <http://url.local/wp-json/>; rel="https://api.w.org/"
                    [X-Content-Type-Options] => nosniff
                    [Access-Control-Expose-Headers] => X-WP-Total, X-WP-TotalPages
                    [Access-Control-Allow-Headers] => Authorization
                    [Expires] => Wed, 11 Jan 1984 05:00:00 GMT
                    [Cache-Control] => no-cache, must-revalidate, max-age=0
                    [Last-Modified] => 
                    [X-WP-Total] => 0
                    [X-WP-TotalPages] => 0
                    [Allow] => GET, POST
                    [Content-Length] => 5
                    [Content-Type] => application/json; charset=UTF-8
                )

            [body:Automattic\WooCommerce\HttpClient\Response:private] => ï»¿[]
        )

    [message:protected] => unexpected character
    [string:Exception:private] => 
    [code:protected] => 200
    [file:protected] => /path/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php
    [line:protected] => 331
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /path/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php
                    [line] => 370
                    [function] => processResponse
                    [class] => Automattic\WooCommerce\HttpClient\HttpClient
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [file] => /path/vendor/automattic/woocommerce/src/WooCommerce/Client.php
                    [line] => 82
                    [function] => request
                    [class] => Automattic\WooCommerce\HttpClient\HttpClient
                    [type] => ->
                    [args] => Array
                        (
                            [0] => webhooks
                            [1] => GET
                            [2] => Array
                                (
                                )

                            [3] => Array
                                (
                                )

                        )

                )

            [2] => Array
                (
                    [file] => /path/test.php
                    [line] => 23
                    [function] => get
                    [class] => Automattic\WooCommerce\Client
                    [type] => ->
                    [args] => Array
                        (
                            [0] => webhooks
                        )

                )

        )

    [previous:Exception:private] => 
)
unexpected character
Code: 200
Body: ï»¿[]
```

Wordpress 4.6.1
WooCommerce 2.6.6

**Comment by bryceadams** [comment]
Any unexpected character/syntax errors are caused on the store/api side, not in this package, so you should look there what's causing it. Perhaps turn on debug mode and then use query string auth to look at the API responses.

**Comment by kgatan** [comment]
I get the same error from two different server, my local development server and the hosted production enviroment.
I also tried against two different sites, 1 existng and one which is brand new.

**Comment by kgatan** [comment]
Is below apache logg message of any use?

`PHP Fatal error:  Uncaught exception 'Automattic\\WooCommerce\\HttpClient\\HttpClientExcep                                       tion' with message 'unexpected character' in /path/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:331\nStack trace:\n#0                                        /path/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(370): Automattic\\WooCommerce\\HttpClient\\HttpClient->processRes                                       ponse()\n#1 /path/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\\WooCommerce\\HttpClient\\HttpClient->request(NULL, '                                       GET', Array, Array)\n#2 /path/test.php(18): Automattic\\WooCommerce\\Client->get()\n#3 {main}\n  thrown in /path/ven                                       dor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 331`
